config/routes.rb
Elp2::Application.routes.draw do
  devise_for :identities

  get "sessions/new"

  get "sessions/create"

  resources :interviews
  resources :interview_questions
  resources :applications
  resources :identities
  resources :lesson_reviews
  resources :lessons
  resources :time_slots
  resources :users
  
  get  '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create', :as => :login
  
  get '/home', to: 'users#home'
  get '/user/view_lesson', to: 'users#view_lesson'
  
  get '/lesson/get_video_keys', to: 'lessons#get_video_keys'
  
  get '/update_online_status', to: 'users#update_online_status'
  
  get '/teacher/schedule', to: 'teachers#schedule'
  get 'load_teachers_schedule', to: 'teachers#load_teachers_schedule'
  get '/teacher/services', to: 'teachers#services'
  get '/teacher/save_service', to: 'teachers#subscribe_to_service'
  get '/teacher/lesson', to: 'teachers#lesson'
  post '/teacher/update_lesson_status', to: 'teachers#update_lesson_status'

  get 'student/favorite_teachers', to: 'students#favorite_teachers'
  get 'student/lessons', to: 'students#lessons'
  get 'student/search', to: 'students#search'
  get 'student/view_teacher', to: 'students#view_teacher'
  get 'student/sign_up', to: 'students#sign_up' 
  get 'student/save_lesson', to: 'students#save_lesson'
  get '/student/lesson', to: 'students#lesson'
  get '/student/lesson_ready', to: 'students#lesson_ready'
  post '/student/update_lesson_status', to: 'students#update_lesson_status'
  get '/student/review_lesson', to: 'lesson_reviews#review_lesson'
  post '/student/add_favorite_teacher', to: 'students#add_favorite_teacher'
  post '/student/remove_favorite_teacher', to: 'students#remove_favorite_teacher'
  get '/student/schedule', to: 'students#schedule'
  get 'load_student_schedule', to: 'students#load_student_schedule'
 
  get '/lesson/lesson', to: 'lessons#lesson'
  get '/lesson/begin_lesson', to: 'lessons#begin_lesson'
  get '/lesson/end_lesson', to: 'lessons#end_lesson'
  post '/lesson/new_message' => 'lessons#new_message', :as => :new_message
  post '/lesson/update_lesson_status', to: 'lessons#update_lesson_status'
  get '/lesson/cancel_class_Teacher', to: 'lessons#cancel_class_teacher'
  get '/lesson/cancel_class_Student', to: 'lessons#cancel_class_student'
  get '/lesson/report_problem', to: 'lessons#report_problem'
  post '/render_filtered_results', to: 'lessons#render_filtered_results'
  

    

    

  

  root  :to => 'home#home'

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :admin_id, :date_applied, :education, :interview_id, :resume_upload, :status, :user_id, :video_interview
  
  def self.submitted
    where(:status => 'submitted')
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_identity!
  ##This locks the whole app will add to specific pages
  before_filter :update_lesson_statuses
  
  @@list_of_states = [ 'scheduled', 'missed', 'recently_taken', 'archived', 'cancelled']
  
  
  
  def update_lesson_statuses
  	@@list_of_states.each_with_index do |state, index|
  		lessons_with_state = Lesson.get_by_status(state)
  		lessons_with_state.each do |lesson|
  			class_time_state = lesson.class_time_state
  			if class_time_state != state
  				lesson.status = class_time_state
  				lesson.save
  			end
  		end
  	end
  end
  
  
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(params[:application])

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :video_interview %><br />
    <%= f.text_field :video_interview %>
  </div>
  <div class="field">
    <%= f.label :interview_id %><br />
    <%= f.number_field :interview_id %>
  </div>
  <div class="field">
    <%= f.label :resume_upload %><br />
    <%= f.text_field :resume_upload %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br />
    <%= f.number_field :admin_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :date_applied %><br />
    <%= f.date_select :date_applied %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Video interview</th>
    <th>Interview</th>
    <th>Resume upload</th>
    <th>Education</th>
    <th>Admin</th>
    <th>Status</th>
    <th>Date applied</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applications.each do |application| %>
  <tr>
    <td><%= application.user_id %></td>
    <td><%= application.video_interview %></td>
    <td><%= application.interview_id %></td>
    <td><%= application.resume_upload %></td>
    <td><%= application.education %></td>
    <td><%= application.admin_id %></td>
    <td><%= application.status %></td>
    <td><%= application.date_applied %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @application.user_id %>
</p>

<p>
  <b>Video interview:</b>
  <%= @application.video_interview %>
</p>

<p>
  <b>Interview:</b>
  <%= @application.interview_id %>
</p>

<p>
  <b>Resume upload:</b>
  <%= @application.resume_upload %>
</p>

<p>
  <b>Education:</b>
  <%= @application.education %>
</p>

<p>
  <b>Admin:</b>
  <%= @application.admin_id %>
</p>

<p>
  <b>Status:</b>
  <%= @application.status %>
</p>

<p>
  <b>Date applied:</b>
  <%= @application.date_applied %>
</p>


<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>