config/routes.rb
Elp2::Application.routes.draw do
  devise_for :identities

  get "sessions/new"

  get "sessions/create"

  resources :interviews
  resources :interview_questions
  resources :applications
  resources :identities
  resources :lesson_reviews
  resources :lessons
  resources :time_slots
  resources :users
  
  get  '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create', :as => :login
  
  get '/home', to: 'users#home'
  get '/user/view_lesson', to: 'users#view_lesson'
  
  get '/lesson/get_video_keys', to: 'lessons#get_video_keys'
  
  get '/update_online_status', to: 'users#update_online_status'
  
  get '/teacher/schedule', to: 'teachers#schedule'
  get 'load_teachers_schedule', to: 'teachers#load_teachers_schedule'
  get '/teacher/services', to: 'teachers#services'
  get '/teacher/save_service', to: 'teachers#subscribe_to_service'
  get '/teacher/lesson', to: 'teachers#lesson'
  post '/teacher/update_lesson_status', to: 'teachers#update_lesson_status'

  get 'student/favorite_teachers', to: 'students#favorite_teachers'
  get 'student/lessons', to: 'students#lessons'
  get 'student/search', to: 'students#search'
  get 'student/view_teacher', to: 'students#view_teacher'
  get 'student/sign_up', to: 'students#sign_up' 
  get 'student/save_lesson', to: 'students#save_lesson'
  get '/student/lesson', to: 'students#lesson'
  get '/student/lesson_ready', to: 'students#lesson_ready'
  post '/student/update_lesson_status', to: 'students#update_lesson_status'
  get '/student/review_lesson', to: 'lesson_reviews#review_lesson'
  post '/student/add_favorite_teacher', to: 'students#add_favorite_teacher'
  post '/student/remove_favorite_teacher', to: 'students#remove_favorite_teacher'
  get '/student/schedule', to: 'students#schedule'
  get 'load_student_schedule', to: 'students#load_student_schedule'
 
  get '/lesson/lesson', to: 'lessons#lesson'
  get '/lesson/begin_lesson', to: 'lessons#begin_lesson'
  get '/lesson/end_lesson', to: 'lessons#end_lesson'
  post '/lesson/new_message' => 'lessons#new_message', :as => :new_message
  post '/lesson/update_lesson_status', to: 'lessons#update_lesson_status'
  get '/lesson/cancel_class_Teacher', to: 'lessons#cancel_class_teacher'
  get '/lesson/cancel_class_Student', to: 'lessons#cancel_class_student'
  get '/lesson/report_problem', to: 'lessons#report_problem'
  post '/render_filtered_results', to: 'lessons#render_filtered_results'
  

    

    

  

  root  :to => 'home#home'

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  attr_accessible :end_time, :start_time, :user_id, :recurrence_pattern
  
  belongs_to :user
  has_one :lesson
  
  #class constants
  @@current_time = DateTime.now
  @@timeslot_max = 3
  
  validates_datetime :end_time, :after => :start_time, :after_message => "must be at after start time"

#   validate :check_timeslot_length

  def check_timeslot_length
    time_diff = Time.diff(end_time,start_time, '%H')
    errors.add(:end_time, " - start_time can't extend #{@@timeslot_max} hours") if time_diff[:hour] >= @@timeslot_max
  end
  
    def pretty_start      
    self.start_time.strftime("%m/%d/%Y, %I:%M %P")   #=> "Printed on 11/19/2007"
  end
  
  def pretty_end
    self.end_time.strftime("%I:%M %P")   #=> "Printed on 11/19/2007"
  end
    

  def recurrence_pattern=(val)
  	newString = "";
  	val.each do |element|
  		newString = newString + element
  	end
  	#newString = newString.gsub(/[^0-9a-z ]/i, '')
    write_attribute(:recurrence_pattern, newString)
  end
  
  def weekly_event_json(start_date, end_date)
  # returns   {id: ts.id, start: ts.start_time.iso8601, end: ts.end_time.iso8601, title: 'Open Slot'} for time slot
    events = []
    recurrence = self.recurrence_pattern
    recurrence.split('').each do |r|
      case r
       when 'M'
        time = end_date.beginning_of_week(:monday)
       when 'T'
        time = end_date.beginning_of_week(:tuesday)
       when 'W'
        time = end_date.beginning_of_week(:wednesday)
       when 'R'
        time = end_date.beginning_of_week(:thursday)
       when 'F'
        time = end_date.beginning_of_week(:friday)
       when 'S'
        time = end_date.beginning_of_week(:saturday)
       when 'N'
        time = end_date.beginning_of_week(:sunday)
       else # the date is a single instance
       time = self.start_time
       end   
      start_time = DateTime.new(time.year, time.month, time.day, self.start_time.hour, self.start_time.min)
      end_time = DateTime.new(time.year, time.month, time.day, self.end_time.hour, self.start_time.min)
      events.push( {:id => self.id, :start => start_time.iso8601, :end => end_time.iso8601, :title => 'title' })
    end
    return events
  end

end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.where(:user_id => current_identity.user_id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_slots }
    end
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
    @time_slot = TimeSlot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_slot }
    end
  end

  # GET /time_slots/new
  # GET /time_slots/new.json
  def new
    @time_slot = TimeSlot.new
    @recurrence_array = []
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_slot }
    end
  end

  # GET /time_slots/1/edit
  def edit
    @time_slot = TimeSlot.find(params[:id])
    @recurrence_array = @time_slot.recurrence_pattern.split(//) 
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(params[:time_slot])
    @time_slot.user_id = current_identity.user_id
	@recurrence_array = []
    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render json: @time_slot, status: :created, location: @time_slot }
      else
        format.html { render action: "new" }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /time_slots/1
  # PUT /time_slots/1.json
  def update
    @time_slot = TimeSlot.find(params[:id])
    @recurrence_array = @time_slot.recurrence_pattern.split(//)
    respond_to do |format|
      if @time_slot.update_attributes(params[:time_slot])
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot = TimeSlot.find(params[:id])
    @time_slot.destroy

    respond_to do |format|
      format.html { redirect_to time_slots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_for(@time_slot) do |f| %>
  <% if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% @time_slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time, {minute_step: 15, ampm: true} %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.time_select :end_time, {minute_step: 15, ampm: true} %>
  </div>
  <div class="field">
    <%= f.label :recurrence_pattern %><br />
    <%= f.select :recurrence_pattern, options_for_select(["M", "T", "W", "R", "F", "S", "N"], @recurrence_array), {}, {:multiple => true, :size => 6}%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_slots/_time_slot.html.erb
    <%= time_slot.start_time %>
    <%= time_slot.end_time %>
    <%= time_slot.recurrence_pattern%>
    <%= link_to 'Show', time_slot %>
    <%= link_to 'Edit', edit_time_slot_path(time_slot) %>
    <%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/time_slots/edit.html.erb
<h1>Editing time_slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<h1>Listing time_slots</h1>


<% @time_slots.each do |time_slot| %>
		<%= render :partial=> "time_slots/time_slot", :locals => {:time_slot => time_slot},  :layout => false%>
<br />
<% end %>

<br />

<%= link_to 'New Time slot', new_time_slot_path %>

app/views/time_slots/new.html.erb
<h1>New time_slot</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>




<p>
  <b>Teacher:</b>
  <%= @time_slot.user_id %>
</p>

<p>
  <b>Start time:</b>
  <%= @time_slot.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @time_slot.end_time %>
</p>


<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>