config/routes.rb
Elp2::Application.routes.draw do
  devise_for :identities

  get "sessions/new"

  get "sessions/create"

  resources :interviews
  resources :interview_questions
  resources :applications
  resources :identities
  resources :lesson_reviews
  resources :lessons
  resources :time_slots
  resources :users
  
  get  '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create', :as => :login
  
  get '/home', to: 'users#home'
  get '/user/view_lesson', to: 'users#view_lesson'
  
  get '/lesson/get_video_keys', to: 'lessons#get_video_keys'
  
  get '/update_online_status', to: 'users#update_online_status'
  
  get '/teacher/schedule', to: 'teachers#schedule'
  get 'load_teachers_schedule', to: 'teachers#load_teachers_schedule'
  get '/teacher/services', to: 'teachers#services'
  get '/teacher/save_service', to: 'teachers#subscribe_to_service'
  get '/teacher/lesson', to: 'teachers#lesson'
  post '/teacher/update_lesson_status', to: 'teachers#update_lesson_status'

  get 'student/favorite_teachers', to: 'students#favorite_teachers'
  get 'student/lessons', to: 'students#lessons'
  get 'student/search', to: 'students#search'
  get 'student/view_teacher', to: 'students#view_teacher'
  get 'student/sign_up', to: 'students#sign_up' 
  get 'student/save_lesson', to: 'students#save_lesson'
  get '/student/lesson', to: 'students#lesson'
  get '/student/lesson_ready', to: 'students#lesson_ready'
  post '/student/update_lesson_status', to: 'students#update_lesson_status'
  get '/student/review_lesson', to: 'lesson_reviews#review_lesson'
  post '/student/add_favorite_teacher', to: 'students#add_favorite_teacher'
  post '/student/remove_favorite_teacher', to: 'students#remove_favorite_teacher'
  get '/student/schedule', to: 'students#schedule'
  get 'load_student_schedule', to: 'students#load_student_schedule'
 
  get '/lesson/lesson', to: 'lessons#lesson'
  get '/lesson/begin_lesson', to: 'lessons#begin_lesson'
  get '/lesson/end_lesson', to: 'lessons#end_lesson'
  post '/lesson/new_message' => 'lessons#new_message', :as => :new_message
  post '/lesson/update_lesson_status', to: 'lessons#update_lesson_status'
  get '/lesson/cancel_class_Teacher', to: 'lessons#cancel_class_teacher'
  get '/lesson/cancel_class_Student', to: 'lessons#cancel_class_student'
  get '/lesson/report_problem', to: 'lessons#report_problem'
  post '/render_filtered_results', to: 'lessons#render_filtered_results'
  

    

    

  

  root  :to => 'home#home'

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  attr_accessible :email, :password_digest, :user_id,:password_confirmation, :remember_me, :password
  
  belongs_to :user
  
    # Include default devise modules. Others available are:
   
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
  #:confirmable, 
  :lockable, :timeoutable and :omniauthable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  # GET /identities
  # GET /identities.json
  def index
    @identities = Identity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @identities }
    end
  end

  def login
 #   if !session[:user_id].blank?
 #     user = User.find(session[:user_id])
 #     user.online = false
 #     user.save
 #   end
 #   reset_session
 #   @channel = "/online_update_status" + @lesson_id
 #   @message = {:user_id => user.id, :status => false}
 #   respond_to do |f|
 #     f.js
 #   end
  end
  
  
  # GET /identities/1
  # GET /identities/1.json
  def show
    @identity = Identity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @identity }
    end
  end

  # GET /identities/new
  # GET /identities/new.json
  def new
    @identity = Identity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @identity }
    end
  end

  # GET /identities/1/edit
  def edit
    @identity = Identity.find(params[:id])
  end

  # POST /identities
  # POST /identities.json
  def create
    @identity = Identity.new(params[:identity])

    respond_to do |format|
      if @identity.save
        format.html { redirect_to @identity, notice: 'Identity was successfully created.' }
        format.json { render json: @identity, status: :created, location: @identity }
      else
        format.html { render action: "new" }
        format.json { render json: @identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /identities/1
  # PUT /identities/1.json
  def update
    @identity = Identity.find(params[:id])

    respond_to do |format|
      if @identity.update_attributes(params[:identity])
        format.html { redirect_to @identity, notice: 'Identity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identities/1
  # DELETE /identities/1.json
  def destroy
    @identity = Identity.find(params[:id])
    @identity.destroy

    respond_to do |format|
      format.html { redirect_to identities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/views/identities/_form.html.erb
<%= form_for(@identity) do |f| %>
  <% if @identity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this identity from being saved:</h2>

      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/identities/edit.html.erb
<h1>Editing identity</h1>

<%= render 'form' %>

<%= link_to 'Show', @identity %> |
<%= link_to 'Back', identities_path %>

app/views/identities/index.html.erb
<h1>Listing identities</h1>

<table>
  <tr>
    <th>User</th>
    <th>Password digest</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @identities.each do |identity| %>
  <tr>
    <td><%= identity.user_id %></td>
    <td><%= identity.password_digest %></td>
    <td><%= identity.email %></td>
    <td><%= link_to 'Show', identity %></td>
    <td><%= link_to 'Edit', edit_identity_path(identity) %></td>
    <td><%= link_to 'Destroy', identity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Identity', new_identity_path %>

app/views/identities/login.html.erb
<!--
<select class="login_select"> 
<% User.all.each do |u| %>
  <option value="<%=u.id%>"> <%=u.last_name%> , <%=u.role%> </option>
  <%end%>
</select>
<button class="login">Login</button>
-->
<%=current_identity.email%>
<script>
  $(function() {
    $('.login').click( function() {
      var select_val = $('.login_select').val();

         window.location.href = "/home?uid=" + select_val; 
      
      });
   

  });
  
</script>

app/views/identities/new.html.erb
<h1>New identity</h1>

<%= render 'form' %>

<%= link_to 'Back', identities_path %>

app/views/identities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @identity.user_id %>
</p>

<p>
  <b>Password digest:</b>
  <%= @identity.password_digest %>
</p>

<p>
  <b>Email:</b>
  <%= @identity.email %>
</p>


<%= link_to 'Edit', edit_identity_path(@identity) %> |
<%= link_to 'Back', identities_path %>