config/routes.rb
Elp2::Application.routes.draw do
  devise_for :identities

  get "sessions/new"

  get "sessions/create"

  resources :interviews
  resources :interview_questions
  resources :applications
  resources :identities
  resources :lesson_reviews
  resources :lessons
  resources :time_slots
  resources :users
  
  get  '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create', :as => :login
  
  get '/home', to: 'users#home'
  get '/user/view_lesson', to: 'users#view_lesson'
  
  get '/lesson/get_video_keys', to: 'lessons#get_video_keys'
  
  get '/update_online_status', to: 'users#update_online_status'
  
  get '/teacher/schedule', to: 'teachers#schedule'
  get 'load_teachers_schedule', to: 'teachers#load_teachers_schedule'
  get '/teacher/services', to: 'teachers#services'
  get '/teacher/save_service', to: 'teachers#subscribe_to_service'
  get '/teacher/lesson', to: 'teachers#lesson'
  post '/teacher/update_lesson_status', to: 'teachers#update_lesson_status'

  get 'student/favorite_teachers', to: 'students#favorite_teachers'
  get 'student/lessons', to: 'students#lessons'
  get 'student/search', to: 'students#search'
  get 'student/view_teacher', to: 'students#view_teacher'
  get 'student/sign_up', to: 'students#sign_up' 
  get 'student/save_lesson', to: 'students#save_lesson'
  get '/student/lesson', to: 'students#lesson'
  get '/student/lesson_ready', to: 'students#lesson_ready'
  post '/student/update_lesson_status', to: 'students#update_lesson_status'
  get '/student/review_lesson', to: 'lesson_reviews#review_lesson'
  post '/student/add_favorite_teacher', to: 'students#add_favorite_teacher'
  post '/student/remove_favorite_teacher', to: 'students#remove_favorite_teacher'
  get '/student/schedule', to: 'students#schedule'
  get 'load_student_schedule', to: 'students#load_student_schedule'
 
  get '/lesson/lesson', to: 'lessons#lesson'
  get '/lesson/begin_lesson', to: 'lessons#begin_lesson'
  get '/lesson/end_lesson', to: 'lessons#end_lesson'
  post '/lesson/new_message' => 'lessons#new_message', :as => :new_message
  post '/lesson/update_lesson_status', to: 'lessons#update_lesson_status'
  get '/lesson/cancel_class_Teacher', to: 'lessons#cancel_class_teacher'
  get '/lesson/cancel_class_Student', to: 'lessons#cancel_class_student'
  get '/lesson/report_problem', to: 'lessons#report_problem'
  post '/render_filtered_results', to: 'lessons#render_filtered_results'
  

    

    

  

  root  :to => 'home#home'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :end_time, :rounded_time, :session_id, :start_time, :student_id, :student_paid, :teacher_id, :teacher_paid, :time_slot_id, :token
  
  belongs_to :teacher, :class_name => "User"
  belongs_to :student, :class_name => "User"
  belongs_to :service
  belongs_to :time_slot
  has_one :lesson_review
  has_one :lesson_problem
  
  
  #class constants
  @@lesson_cancel_threshold = 5.hours
  @@lesson_ready_threshold = 30.minutes
  
  
  def weekly_event_json(user_type)
  # returns   {id: ts.id, start: ts.start_time.iso8601, end: ts.end_time.iso8601, title: 'Teacher Name'} for scheduled lesson
#      start_time = DateTime.new(self.year, time.month, time.day, self.start_time.hour, self.start_time.min)
#      end_time = DateTime.new(time.year, time.month, time.day, self.end_time.hour, self.start_time.min)
      if user_type === 'teacher'
        user_name = self.student.name
      else 
        user_name = self.teacher.name
      end
      return [{
          :id => self.id, 
          :start => self.start_time.iso8601, 
          :end => self.end_time.iso8601, 
          :title => 'Lesson with ' + user_name,
          :color => 'red'
        }]
      
  end
  
  def lesson_cancel_threshold_time
	 	return Time.now - @@lesson_cancel_threshold
	end
  
  def time_before_show_ready(start_time) 
  	return start_time - @@lesson_ready_threshold
 end
 
  def allow_lesson_cancel
    Time.now < lesson_cancel_threshold_time
  end

  def calculate_cost
    #grab lesson rate (or teacher rate if lesson rate null)
    if self.rate.blank?
      self.rounded_time * self.teacher.rate
    else
      self.rounded_time * self.rate
    end
  end
  
  def cancel(user_role)
    if user_role == 'teacher'
      if self.time_slot.start_time < lesson_cancel_threshold_time 
        self.cancelled = true
      else
        return false
      end
    else
      if self.time_slot.start_time < lesson_cancel_threshold_time 
        self.cancelled = true
      else
        false
      end      
    end
  end
  
  def cancelled
  	self.status == 'cancelled'
  end
  
  def self.cancelled
  	where(:status => 'cancelled')
  end
  
  def class_time_state
    #A class can be missed, taken, scheduled, rescheduled, or cancelled.
    if self.missed
      'missed'
    elsif self.taken
      'taken'
    elsif self.scheduled
      'scheduled'
    #elsif self.rescheduled
      #'rescheduled
    elsif self.cancelled
      'cancelled'
    end
  end
  
  def end_lesson
    #mark end time and save rounded total time
    self.end_time = Time.now
    self.rounded_time = end_time - start_time
  end
  
  def missed
    self.end_time.blank? && self.time_slot.end_time <= Time.now && !self.cancelled && !self.taken
  end
  
  def self.missed
  	self.missed
  end
  
  def missed_by_both
    self.missed_by_student && self.missed_by_teacher
  end
  
  def missed_by_student
    !self.student_ready
  end
  
  def missed_by_teacher
    !self.teacher_ready
  end
  
  def pretty_end
    self.end_time.strftime("%m/%d/%Y, %H:%M")   #=> "Printed on 11/19/2007"
  end
  
  def pretty_start      
    self.start_time.strftime("%m/%d/%Y, %H:%M")   #=> "Printed on 11/19/2007"
  end
  
  def pretty_time_till
 #     debug_time = self.time_slot.start_time - 48.days
#     Time.now = debug_time
    time_diff = Time.diff( time_slot.start_time, Time.now, '%d')
    show_reasonable_time(self.time_slot.start_time, time_diff) 
  end
  
  def ready_to_start
     self.student_ready and self.teacher_ready and self.teacher.online and self.student.online
  end
  
  def report_problem(problem)
    lesson_problem = self.lesson_problem.build
    lesson_problem.problem = problem
    lesson_problem.save
  end
  
  def scheduled
    self.time_slot.start_time >= Time.now
  end
  
  def show_ready
  	puts 'check scheduled'
  	puts self.scheduled
  	puts Time.now
    Time.now >= time_before_show_ready(self.time_slot.start_time) && self.scheduled
  end
  
  
  def show_reasonable_time(start_time, time_diff) 
    #Do not want to show large time values in hours or minutes. 
    if start_time >= Time.now #class is in future
      if time_diff[:week] >= 1 or time_diff[:month] >= 1 or time_diff[:year] >= 1
        #'Class is on ' + start_time.strftime("%m/%d/%Y, %I:%M %P") + ', 
        'Class is in ' + time_diff[:diff]
      elsif time_diff[:day] >= 1
        'Class is coming up in ' + time_diff[:day].to_s + ' days.'
        #'On ' + start_time.strftime("%m/%d/%Y, %I:%M %P") + ', 
      elsif time_diff[:hour] >= 6
        #'Class is today at ' + start_time.strftime("%I:%M %P") + '! 
        'You have ' + time_diff[:hour].to_s + ' hours.' 
      else
        #show time
        #'Class begins at ' + start_time.strftime("%I:%M %P") + '! 
        'You have ' +
         time_diff[:hour].to_s + ' hours and ' +time_diff[:minute].to_s + ' minutes.'
      end
    else #Class is in past
      if time_diff[:week] >= 1 or time_diff[:month] >= 1 or time_diff[:year] >= 1
        #'Class is on ' + start_time.strftime("%m/%d/%Y, %I:%M %P") + ', 
        'Class was scheduled for ' + time_diff[:diff] + ' ago.'
      elsif time_diff[:day] >= 1
        'Class was scheduled for ' + time_diff[:day].to_s + ' days ago.'
        #'On ' + start_time.strftime("%m/%d/%Y, %I:%M %P") + ', 
      elsif time_diff[:hour] >= 6
        #'Class is today at ' + start_time.strftime("%I:%M %P") + '! 
       'Class was ' + time_diff[:hour].to_s + ' hours ago.'
      else
        #show time
        #'Class begins at ' + start_time.strftime("%I:%M %P") + '! 
        'Class was taken ' +
         time_diff[:hour].to_s + ' hours and ' +time_diff[:minute].to_s + ' minutes ago.'
      end
    end
  end
  
  def self.get_by_status(status)
  	where(status: status)
  end
  
  def taken
    !self.end_time.blank? && self.end_time <= Time.now
  end
  
  def update_student_status(status)
     if status == 'true'
       self.student_ready = true
     else
       self.student_ready = false
     end
  end
  
  def update_teacher_status(status)
    puts status
    puts "CHECK STATUS"
    if status == 'true'
        self.teacher_ready = true
    else
        self.teacher_ready = false
    end
    self.save
  end
    
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationsController
layout nil
layout 'application', :except => :render_filtered_results

  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
  
  def render_filtered_results
  @teachers = User.teachers
  @teachers = @teachers.filter_selections(params) 
    render :partial => "render_filtered_results"
  end
  
  def begin_lesson
    start_time = params[:start_time].to_datetime
    lesson = Lesson.find(params[:lesson_id])
    lesson.start_time = start_time
    if lesson.save
      msg = "Success"
    else
      msg = "Failure"
    end
    render :text => msg
   end
  
  def end_lesson
    end_time = params[:end_time].to_datetime
    lesson = Lesson.find(params[:lesson_id])
    lesson.end_time = end_time
    rounded_time = ((end_time.to_f - lesson.start_time.to_f) / 60.0).to_f
    lesson.rounded_time = rounded_time
    puts lesson.rounded_time
    puts lesson.end_time
    puts lesson.start_time
    puts "check here"
    if lesson.save
      msg = lesson.rounded_time.to_s
    else
      msg = "Failure"
    end
    render :text => msg
   end
  
  def get_video_keys
    puts 'get video keys'
		keysHash = {}
		config_opentok
    puts params
    @lesson = Lesson.find(params[:lid])
    if @lesson.session_id.blank?
      session = @opentok.create_session(['p2p.preference','enabled'])
      @lesson.session_id = session.session_id
	  	@lesson.token = session.generate_token
      @lesson.save
    else
      session_id = @lesson.session_id
      token = @lesson.token
      puts "check token info"
      puts token
    end
				
    keysHash[:sessionID] = @lesson.session_id
    keysHash[:token] = @lesson.token
    render :json => keysHash.to_json
  end
  
  
	def studentAccept
		keysHash = {}
		#temporary settings to develop video chatting
    @lesson = Lesson.find(params[:lid])
		keysHash[:sessionID] = @lesson.session_id
    keysHash[:token] = @lesson.token
		
		render :json => keysHash.to_json	
	end
  
  def new_message
    @lesson_id = params[:lid]
    @other_user_id = params[:uid]
    @channel = "/lesson/private/" + @lesson_id.to_s + "/" + @other_user_id.to_s
    puts 'Check channel' + @channel
    @message = {:msg => params[:message]}
    respond_to do |f|
      f.js
    end
  end
  
  
 def update_lesson_status
    puts params
   @user = User.find(current_identity.user_id)
    @lesson_id = params[:lid]
    lesson = Lesson.find(@lesson_id)
    status = params[:ready]
   if lesson.student == @user
     lesson.update_student_status(status)
   else
     lesson.update_teacher_status(status)
   end
   puts 'CHECK IT' + lesson.teacher_ready.to_s
   if lesson.save
      @channel = "/other_user_updates/" + @lesson_id.to_s + "/" + @user.id.to_s     
      @message = {:status => status, :start_lesson => lesson.ready_to_start}
      puts @message
      respond_to do |f|
        f.js
      end
    end
  end
    
  def lesson
     user = User.find(current_identity.user_id)
#      @teacher = false
    ### This is where I will grab the token and session id
    @current_time = Time.now
    lesson = Lesson.find(params[:lesson_id])
    @lesson_id = lesson.id
    @user_id = user.id
    @pretty_time_till = lesson.pretty_time_till
    if lesson.teacher_ready
      @teacherStatus = 'Ready'
    else
      @teacherStatus = 'Not Ready'
    end
    if lesson.student_ready
      @studentStatus = 'Ready'
    else
      @studentStatus = 'Not Ready'
    end
    if lesson.teacher_ready and lesson.student_ready
      @ready_to_start = true
    else
      @ready_to_start = false
    end
    if user == lesson.teacher
      @otherUser = lesson.student
      @userStatus = @teacherStatus
      @otherUserStatus = @studentStatus
      @typeOfUser = 'Teacher'
    else
      @otherUser = lesson.teacher
      @userStatus = @studentStatus
      @otherUserStatus = @teacherStatus
      @typeOfUser = 'Student'
    end
    #@teacher_user = @lesson.teacher
    #@teacher_paid = @lesson.teacher_paid
    #@student_paid =  @lesson.student_paid
    timeslot = lesson.time_slot 
    @start_time = timeslot.pretty_start
    @end_time =timeslot.pretty_end
    case lesson.class_time_state
    when 'missed'
      @missed_class = true
      if lesson.missed_by_both
        missed_by = 'both'
      elsif lesson.missed_by_student
        missed_by = 'student'
      else
        missed_by = 'teacher'
      end
      @message = "This class was missed by " + missed_by
      render 'missed_class'
    when 'taken'
      @taken_class = true
      @message = "This class was taken"
    when 'scheduled'
      @show_ready = lesson.show_ready
      @scheduled_class = true
      @message = "This class is currently scheduled"
    when 'cancelled'
      @cancelled_class = true
      @message = "This class was cancelled"
    end
      #There are different rules on whether a teacher or student can cancel a class
    @show_cancel_lesson = lesson.allow_lesson_cancel
  end
  
    def class_time_state
    #A class can be missed, taken, scheduled, rescheduled, or cancelled.
    if self.missed
      'missed'
    elsif self.taken
      'taken'
    elsif self.scheduled
      'scheduled'
    #elsif self.rescheduled
      #'rescheduled
    elsif self.cancelled
      'cancelled'
    end
  end
  
  
  def cancel_class_teacher
    lesson = Lesson.find(params[:lid])
    lesson.cancel('teacher')
    lesson.save
    flash[:notice] = "Lesson successfully cancelled."
    redirect_to '/teacher/schedule'
  end
  
  def cancel_class_student
    lesson = Lesson.find(params[:lid])
    lesson.cancel('student')
    lesson.save
    flash[:notice] = "Lesson successfully cancelled."
  #  redirect_to '/teacher/schedule'
  end
  
  def end_lesson
    #need time class was taken and cost
    lesson = Lesson.find(params[:lesson])
    lesson.end
    #return time class was taken
  end
    
    def lesson_cost
      lesson = Lesson.find(params[:lesson])
      lesson.calculate_cost
    end
    
    def report_problem
      lesson = Lesson.find(params[:lesson])
      lesson.report_problem(params[:problem])
    end
      
      
  private

	def config_opentok
		if @opentok.nil? 
			@opentok = OpenTok::OpenTok.new '45188672', '63b02dc234a56ada8d0aeeed1f90fb8930efaffd'

		end
	end

end

app/helpers/lessons_helper.rb
module LessonsHelper
    def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block)}
    uri = URI.parse("http://steady-box-12-181649.use1-2.nitrousbox.com:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end

  
end

app/views/lessons/_render_filtered_results.html.erb
<h3> List of Teachers </h3>
		<%@teachers.each do |t|%>
			<%= render :partial=> "users/teacher", :locals => {:teacher => t, :page => 'search_lessons'},  :layout => false%>
		<%end%>

app/views/lessons/index.html.erb
<h1>Listing lessons</h1>

<table>
  <tr>
    <th>Teacher</th>
    <th>Student</th>
    <th>Time slot</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Rounded time</th>
    <th>Student paid</th>
    <th>Teacher paid</th>
    <th>Token</th>
    <th>Session</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lessons.each do |lesson| %>
  <tr>
    <td><%= lesson.teacher_id %></td>
    <td><%= lesson.student_id %></td>
    <td><%= lesson.time_slot_id %></td>
    <td><%= lesson.start_time %></td>
    <td><%= lesson.end_time %></td>
    <td><%= lesson.rounded_time %></td>
    <td><%= lesson.student_paid %></td>
    <td><%= lesson.teacher_paid %></td>
    <td><%= lesson.token %></td>
    <td><%= lesson.session_id %></td>
    <td><%= link_to 'Show', lesson %></td>
    <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
    <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/lesson.html.erb
<h3>Lesson Page for <%=@typeOfUser%></h3>
<%if @message%>
<%=@message%>
<%end%>
<p><%=@pretty_time_till%></p>

<table>
  <tr><td>Class Time</td><td><%=@start_time%> - <%=@end_time%></td></tr>
  
  <%if @show_ready%>
    <tr><td>Status</td><td><% if @userStatus == 'Ready'%><button class="status ready">Ready</button>
                            <%else%><button class="status not_ready">Not Ready</button> 
                            <%end%></td></tr>
    <tr><td>Other User's Status</td><td><div id="other_user_ready"><%=@otherUserStatus%></div></td></tr>
  <%end%>
  <tr><td>Other User Online?</td><td><div id="user_online_<%=@otherUser.id%>"><%=@otherUser.online%></div></td></tr>
  <%if @show_end_lesson%>
  <tr class="endLessonRow"><td>End Lesson</td><td><a href="/student/review_lesson?lid=<%=@lesson_id%>">End Lesson</a></td></tr>
  <%end%>
  <%if @show_cancel_lesson %>
  <tr><td>Cancel Class</td><td><%=link_to "Cancel Lesson", "/lesson/cancel_class_#{@typeOfUser}?lid=#{@lesson_id}", :confirm => ("Are you sure you want to cancel this lesson?")%></td></tr>
  <%end%>


  <!---<p><button id="start_lesson" style="display:<%if !@ready_to_start%>none<%end%>">Start Lesson</button> </p>--->
</table>


<%= subscribe_to "/lesson/private/#{@lesson_id}/#{@user_id}" %>
<%= subscribe_to "/other_user_updates/#{@lesson_id}/#{@otherUser_id}" %>
<!-- /user_updates/#{@lesson_id} --->
  
<div id="chat">

</div>

<%= form_tag new_message_path, :remote => true do %>
  <%= text_field_tag :message %>
<%= hidden_field_tag(:lid, value = @lesson_id)%>
  <%= hidden_field_tag(:uid, value = @otherUser.id)%>
<%= submit_tag "Send", :id => "send_message" %>
<% end %>


<div class="container">
<div class="row">
  <!--
<div class="col-xs-12"><button class="btn btn-large btn-success todays_lesson" id="<%=@lesson_id%>"><%if @teacher%>Teach<%else%>Take<%end%> today's lesson</button> -->

<div id="subscriberContainer"></div>
<div id="myPublisherDiv"></div>

<button class="toggleVideo" value=0 style="display:none">Toggle Video </button>

<style>
  .ready {
    background-color: 'green';
  }
  .not_ready {
    background-color: 'red';
  }
  
  .endLessonRow {
    display: 'none';
  }
</style>
<script>
  
$(document).ready(function() {
 //OPENTOK

      // Initialize API key, session, and token...
      // Think of a session as a room, and a token as the key to get in to the room
      // Sessions and tokens are generated on your server and passed down to the client
      var apiKey = "45188672"; 
      var sessionId; //="2_MX40NTE1OTg3Mn5-MTQyNDM5MjUyNzgxOH5BbDV0blZxOHkxWXZGUGJvallMOVk1WUR-fg";
      var token;// =  "T1==cGFydG5lcl9pZD00NTE1OTg3MiZzaWc9ZGZlNmM1NGNjNWRiYjI5MmU2ODE3ZjBjNTZlYjNkYzA0YTExYjIzNzpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTJfTVg0ME5URTFPVGczTW41LU1UUXlORE01TWpVeU56Z3hPSDVCYkRWMGJsWnhPSGt4V1haR1VHSnZhbGxNT1ZrMVdVUi1mZyZjcmVhdGVfdGltZT0xNDI0MzkyNTU3Jm5vbmNlPTAuNTc5MjQ3MjAzODcxOTM3Ng==";
	  var session;
	  var subscriber;
	  var stream;
	  var subscriberProperties;
	  var publisherName;
	  var pHeight = 100;
	  var pWidth = 150;
	  var sHeight = 400;
	  var sWidth = 600;
	  var videoResolution = "1280x720";
	  var videoFrameRate = 30;	
	  var otherUserReady;
    var streamStarted = false;

  
    $('.endLessonRow').hide();
  
//  if ($('#other_user_ready').text() == 'Ready') {
  if ($('#t_ready').text() == 'Ready') {
       otherUserReady = true;
     }
  else {
       otherUserReady = false;
  }
  
    $.ajax({
    	method: 'GET',
        url: '/lesson/get_video_keys?lid=<%=@lesson_id%>',
        dataType: 'json',	
        async: false,
        success: function(keysHash) {
        //	publisherName = keysHash.studentName;
       		sessionID = keysHash.sessionID;
       		token = keysHash.token;
       		session = OT.initSession(apiKey, sessionID);
    }
    });
  
 
   
    PrivatePub.subscribe("/lesson/private/<%=@lesson_id%>/<%=@user_id%>", function(data) {
         addToChat(data.msg);
      // add data.msg to chat
  });
   function addToChat(message) {
     $('#chat').append('<p>' + message + '</p>');
   }
  $('#send_message').click(function() {
    $('#message').val('');
  })
//    PrivatePub.subscribe("/other_user_updates/<%=@lesson_id%>", function(data) {

    PrivatePub.subscribe("/other_user_updates/<%=@lesson_id%>/<%=@otherUser_id%>", function(data) {
      console.log(data);
      if (data.status == 'true') {
        otherUserReady = true;
       // $('#other_user_ready').text("Ready.");
        $('#other_user_ready').text("Ready.");
      } 
      else {
        otherUserReady = false;
       // $('#other_user_ready').text("Not Ready.");
       $('#other_user_ready').text("Not Ready.");
      }
      if (data.start_lesson) {
        $('#start_lesson').show();
      }
      else {
        $('#start_lesson').hide();
      }
      });   
 
  $('body').on('click', '.not_ready', function() {
   //    $.ajax({ url:'/lesson/update_lesson_status', type:'POST', data: {'lid': '<%=@lesson_id%>', 'ready': 'true'} });
    $.ajax({ url:'/lesson/update_lesson_status', type:'POST', data: {'lid': '<%=@lesson_id%>', 'ready': 'true'} });
    $(this).removeClass('not_ready').addClass('ready');
    $(this).text('Ready');
     startVideo();
   });

   $('body').on('click', '.ready', function() {
    //     $.ajax({ url:'/lesson/update_lesson_status', type:'POST', data: {'lid': '<%=@lesson_id%>', 'ready': 'false'} });
     $.ajax({ url:'/lesson/update_lesson_status', type:'POST', data: {'lid': '<%=@lesson_id%>', 'ready': 'false'} });
     $(this).removeClass('ready').addClass('not_ready');
     $(this).text('Not Ready');
   });

  
     


/*
  session.connect(token, function(error) {
    var publisher = OT.initPublisher();
    session.publish(publisher);
  });
  */  
     
  // This is the other user, connecting in
	session.on("streamCreated", function (event) {
    if (confirm('Start class?')) {
        if (!streamStarted) {
         publishVideo();
        }
        stream = event.stream;
        subscriberProperties = {insertMode: "append", height: sHeight, width: sWidth};
        subscriber = session.subscribe(stream, 'subscriberContainer', subscriberProperties, function (error) {
        if (error) {
          console.log(error);
        }
        else {
          console.log("Subscriber added.");
        }
        });
  }
	});

     // This is the current user, smaller screen
function startVideo() {
     session.connect(token, function(error) {
    if (error) {
    alert("Error connecting: ", error.code, error.message);
      } 
     else {
       		publisherProperties = {name: publisherName, width: pWidth, height: pHeight, resolution: videoResolution,
	    							frameRate: videoFrameRate};
           if (otherUserReady) {
              publishVideo();
           }
      }
     }); 
  };

  function publishVideo() {
      publisher = OT.initPublisher('myPublisherDiv', publisherProperties);
     session.publish(publisher);
    streamStarted = true;
  }

  function endVideo() {
		/*session.unsubscribe(stream);
		session.unpublish(publisher);
    */
   window.href.location = '/review_lesson?id=<%@lesson_id%>'
    
  }
     
     
/*
	$('.unsubscribe').click(function() {
	});
	
	
	$('.unpublish').click(function() {
	});
	
	$('.resizeVideo').click(function() {
    	var pubElement = $('#myPublisherDiv');
    	pubElement.css("width","100");
    	pubElement.css("height","100");
  	});
  	*/
  	$('.toggleVideo').click(function() {
  		if ($(this).val() == 0 ) {
  			$(this).val(1);
  			$(this).html('Turn Video On');
  			publisher.publishVideo(false);
  		}
  		else {
  			$(this).val(0);
  			$(this).html('Turn Video Off');
  			 publisher.publishVideo(true);
  		}
  	});
  
   // If user was ready on entrance- run startVideo
     if ($('.status').text() == 'Ready') {
       startVideo();
     }
  	/*
  	
  	var start = new Date;

	setInterval(function() {
    	$('.Timer').text((new Date - start) / 1000 + " Seconds");
	}, 1000);
*/	
   });
     
  
  
</script>

app/views/lessons/missed_class.html.erb
<%=@message%>

app/views/lessons/new_message.js.erb
// Send the message
<% publish_to @channel, @message %>

app/views/lessons/update_lesson_status.js.erb
// Send the message
<% publish_to @channel, @message %>